-- 코드를 입력하세요
SELECT AUTHOR.AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(SALES*PRICE) AS TOTAL_SALES
FROM BOOK, AUTHOR, BOOK_SALES
WHERE BOOK.AUTHOR_ID = AUTHOR.AUTHOR_ID AND BOOK.BOOK_ID = BOOK_SALES.BOOK_ID
    AND DATE(SALES_DATE) >= '2022-01-01' AND DATE(SALES_DATE) < '2022-02-01'
GROUP BY AUTHOR.AUTHOR_ID, CATEGORY
ORDER BY AUTHOR_ID ASC, CATEGORY DESC