-- 코드를 입력하세요
SELECT FP.PRODUCT_ID, PRODUCT_NAME, SUM(PRICE*AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT FP JOIN FOOD_ORDER FO ON FP.PRODUCT_ID = FO.PRODUCT_ID
WHERE YEAR(PRODUCE_DATE)='2022' AND MONTH(PRODUCE_DATE)='05'
GROUP BY FP.PRODUCT_CD
ORDER BY TOTAL_SALES DESC, FP.PRODUCT_ID ASC;