-- 코드를 입력하세요
SELECT U2.USER_ID, NICKNAME, SUM(PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD AS U1
    JOIN USED_GOODS_USER U2
    ON U1.WRITER_ID = U2.USER_ID
WHERE STATUS = 'DONE'
GROUP BY U1.WRITER_ID
HAVING SUM(PRICE)>=700000
ORDER BY TOTAL_SALES ASC;