-- 코드를 입력하세요
WITH RECURSIVE TIME AS(
    SELECT 9 AS HOUR
    UNION ALL
    SELECT HOUR+1
    FROM TIME
    WHERE HOUR<19
)

SELECT T.HOUR, COUNT(A.ANIMAL_ID) AS COUNT
FROM ANIMAL_OUTS A RIGHT JOIN TIME T ON T.HOUR = HOUR(A.DATETIME)
GROUP BY T.HOUR
ORDER BY T.HOUR ASC