-- 코드를 입력하세요
SELECT MONTH(START_DATE) AS MONTH, CAR_ID, COUNT(HISTORY_ID) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE CAR_ID IN (
    SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE DATE(START_DATE) >= '2022-08-01' AND DATE(START_DATE) < '2022-11-01'
        GROUP BY CAR_ID
        HAVING COUNT(HISTORY_ID) >= 5
) AND DATE(START_DATE) >= '2022-08-01' AND DATE(START_DATE) < '2022-11-01'
GROUP BY CAR_ID, MONTH(START_DATE)
ORDER BY MONTH ASC, CAR_ID DESC

