-- 코드를 작성해주세요
SELECT YEAR(ED.DIFFERENTIATION_DATE) AS YEAR, MAX_OF_YEAR-SIZE_OF_COLONY AS YEAR_DEV,ED.ID
FROM ECOLI_DATA AS ED
    JOIN (SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAX_OF_YEAR
         FROM ECOLI_DATA
         GROUP BY YEAR(DIFFERENTIATION_DATE)) AS ED2
    ON YEAR(ED.DIFFERENTIATION_DATE) = ED2.YEAR
ORDER BY YEAR ASC, YEAR_DEV ASC
