-- 코드를 입력하세요
SELECT INGREDIENT_TYPE, SUM(TOTAL_ORDER) AS TOTAL_ORDER
FROM (SELECT INGREDIENT_TYPE, SUM(TOTAL_ORDER) AS TOTAL_ORDER
FROM FIRST_HALF F
    JOIN ICECREAM_INFO I
    ON F.FLAVOR = I.FLAVOR
GROUP BY F.FLAVOR
ORDER BY TOTAL_ORDER ASC) AS A
GROUP BY INGREDIENT_TYPE
ORDER BY TOTAL_ORDER ASC